// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ9fl15ccYhwT8b0p979vPMiSpSqjbVLM',
    appId: '1:1073522099644:android:5bc086f0d831979c9557b9',
    messagingSenderId: '1073522099644',
    projectId: 'hydroponic-monitoring-sandbox',
    databaseURL: 'https://hydroponic-monitoring-sandbox-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydroponic-monitoring-sandbox.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdEwZjuLjwWiTzXBwZzI6QKjXHiL6BrH0',
    appId: '1:1073522099644:ios:cfae0b578f7d6d479557b9',
    messagingSenderId: '1073522099644',
    projectId: 'hydroponic-monitoring-sandbox',
    databaseURL: 'https://hydroponic-monitoring-sandbox-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hydroponic-monitoring-sandbox.firebasestorage.app',
    iosBundleId: 'com.example.hydroponic',
  );

}